#!/bin/sh
#
# cstk:dec - decrypt a file from safe storage using openssl
# clearly this depends upon openssl being installed and in
# the path.  if this is not the case, you are likely not
# running a supported system.

if [ "x${1}" = "x" ]; then
	echo "You need to supply a single argument, a file to decrypt."
	exit 1
fi

openssl aes-256-cbc -d -salt -in "${1}" -out decrypted."${1}"
if [ $? -eq 0 ]; then
	rm -f "${1}"
	mv decrypted."${1}" "${1}"
	chmod a-w "${1}"
	echo "${1} replaced with decrypted content."
else
	echo "Decryption failed, aborting operation."
	exit 1
fi

exit 0
