#!/bin/sh
#
# cstk:enc - encrypt a file for safe storage using openssl
# clearly this depends upon openssl being installed and in
# the path.  if this is not the case, you are likely not
# running a supported system.

if [ "x${1}" = "x" ]; then
	echo "You need to supply a single argument, a file to encrypt."
	exit 1
fi

openssl aes-256-cbc -salt -in "${1}" -out "${1}".encrypted
if [ $? -eq 0 ]; then
	rm -f "${1}"
	mv ${1}.encrypted "${1}"
	chmod a-w "${1}"
	echo "${1} replaced with encrypted content."
else
	echo "Encryption failed, aborting operation."
	exit 1
fi

exit 0
